ci: split run_sudo jobs

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -120,8 +120,8 @@ jobs:
     - name: test CS
       run: /opt/racketcs/bin/racket -e '(displayln 42)'
 
-  run_sudo:
-    name: "Install as root and user"
+  run_sudo_never:
+    name: "Install as user"
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
@@ -138,35 +138,57 @@ jobs:
     - name: npm build
       run: npm build
 
-    - name: install non-sudo version
+    - name: install Racket as user
       run: node lib/setup-racket.js
       env:
         INPUT_VARIANT: 'CS'
         INPUT_VERSION: '7.9'
-        INPUT_DEST: '${HOME}/racket-user'
+        INPUT_DEST: '${HOME}/racket'
         INPUT_SUDO: never
 
-    - name: install sudo version
+    - name: test Racket
+      run: |
+        ${HOME}/racket/bin/racket -ve- '(displayln 42)'
+
+    - name: test package installation
+      run: |
+        ${HOME}/racket/bin/raco pkg install -i --skip-installed --no-docs --auto racket-test-core
+
+  run_sudo_always:
+    name: "Install as root"
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@master
+
+    - name: Set Node.js 10.x
+      uses: actions/setup-node@master
+      with:
+        node-version: 10.x
+
+    - name: npm install
+      run: npm install
+
+    - name: npm build
+      run: npm build
+
+    - name: install Racket as root
       run: node lib/setup-racket.js
       env:
         INPUT_VARIANT: 'CS'
         INPUT_VERSION: '7.9'
-        INPUT_DEST: '/opt/racket-root'
+        INPUT_DEST: '/opt/racket'
         INPUT_SUDO: always
 
     - name: test Racket
       run: |
-        ${HOME}/racket-user/bin/racket -ve- '(displayln 42)'
-        /opt/racket-root/bin/racket -ve- '(displayln 42)'
+        /opt/racket/bin/racket -ve- '(displayln 42)'
 
-    - name: test user packages
-      run: '${HOME}/racket-user/bin/raco pkg install -i --skip-installed --no-docs --auto racket-test-core'
-
-    - name: test root packages
-      id: rootpkg
-      run: '/opt/racket-root/bin/raco pkg install -i --skip-installed --no-docs --auto racket-test-core'
-      continue-on-error: true
-
-    - name: check that racket-root is installed as root
-      if: ${{ always() && steps.rootpkg.outcome != 'failure' }}
-      run: exit 1
+    - name: test package installation
+      run: |
+        if ! /opt/racket/bin/raco pkg install -i --skip-installed --no-docs --auto racket-test-core; then
+          echo "XFAIL"
+        else
+          echo "Non-root package installation should have failed."
+          exit 1
+        fi
